### ISSUE TITLE
Feature request: Use highlighting to indicate errors

### ISSUE THREAD

**Issue by lervag** [w0rp/ale#187] opened 2016-11-24 22:09 UTC
I'm not sure if this is even possible, but if it is: It would be very convenient if we could get some sort of syntax highlighting of errors/warnings instead of/in addition to the signs. I prefer to not have signs, but I would like some visual cue of the error, e.g. underline or coloring.

**Comment by w0rp** [comment] 2016-11-25 12:53
It's possible. I plan to add this eventually. You can set syntax rules for a given buffer number, line, and column range. It's just a bit of a trick to get it working properly.

**Comment by lervag** [comment] 2016-11-25 12:55
I reckon it is! In the meantime: Great work with this plugin, I've just replaced syntastic and I couldn't be happier. :)

**Comment by w0rp** [comment] 2017-01-13 09:50
I just noticed that this is a duplicate of #171.

**Closed by w0rp** 2017-01-13 09:50 UTC
