### ISSUE TITLE
'Disable linter x' == 'enable every linter except x'?

### ISSUE THREAD

**Issue by srsudar** [w0rp/ale#1505] opened 2018-04-16 18:00 UTC
I'm trying to figure out how to disable a linter. The [FAQ makes it look like](https://github.com/w0rp/ale#5i-how-do-i-disable-particular-linters) to disable a linter I have to tell ALE which linters to run rather than just telling it which not to run:

> By default, all available tools for all supported languages will be run. If you want to only select a subset of the tools, simply create a g:ale_linters dictionary in your vimrc file mapping filetypes to lists of linters to run.

Am I reading that correctly? `proselint` and `alex` are both very opinionated, eg. If I do not want to use them it looks like I need to construct a multiline dictionary and manually keep it up to date with the list of linters ALE supports by default.

It seems more natural to me in this case (though perhaps not generally) to have an option to tell it which not to use, rather than tell it which to use. Is there a way to do this?

My apologies if I've misread something or failed to find an existing issue addressing this. I found a pointer back to the FAQ in an issue but not a more detailed answer to this question.

**Comment by w0rp** [comment] 2018-04-16 18:36
Duplicate of #1453

**Closed by w0rp** 2018-04-16 18:36 UTC
