### ISSUE TITLE
Extra newline causes TypeScript linter to complain on win32

### ISSUE THREAD

**Issue by mikeperri** [w0rp/ale#280] opened 2017-01-27 17:03 UTC
One of the lint rules for TypeScript TSLint disallows [consecutive blank lines](https://palantir.github.io/tslint/rules/no-consecutive-blank-lines/). Unfortunately, it seems like ALE on win32 is adding an extra newline to the end of the buffer. So TSLint will always raise this error at the last line of any TypeScript file.

ALE adds the newline for win32/NeoVim here:
https://github.com/w0rp/ale/blob/master/autoload/ale/engine.vim#L291-L306

Is it necessary to add the newline (at the end of line 299)? I understand channel is in NL mode, so we need to add a newline to terminate a message. But I took it out, and TSLint still works, and it doesn't raise the error about consecutive blank lines. Am I missing something?

I haven't tried this in NeoVim but I figure it might have the same issue.

**Comment by w0rp** [comment] 2017-01-30 15:11
This is an interesting issue to fix. I suspect the problem is in the stdin_wrapper script, right here:

https://github.com/w0rp/ale/blob/master/stdin-wrapper.bat#L16

I don't know of a way to perfectly copy bytes from stdin to a file in a Batch script. If anyone knows a way, please let me know. It requires some Batch witchery.

**Comment by w0rp** [comment] 2017-03-29 00:00
@mikeperri Are you still experiencing this issue? I believe the issue may have already been fixed, but maybe not. I'll test this on Windows probably tomorrow myself.

**Comment by mikeperri** [comment] 2017-03-30 18:49
@w0rp I'm not having the issue anymore on Windows.

**Comment by w0rp** [comment] 2017-03-31 06:45
Nice, thank you for commenting. I believe it was the Batch script which caused the issues. I was able to replace that script with a VimL implementation a while ago, which by and large works the same way everywhere. So, I'm glad it's working now.

I might retroactively update the patch notes of whatever version contains the fix for this.

**Closed by w0rp** 2017-03-31 06:45 UTC
Labels: bug
