### ISSUE TITLE
Vint broken

### ISSUE THREAD

**Issue by bounceme** [w0rp/ale#125] opened 2016-10-20 06:59 UTC
using vint version 0.3.9 on both neovim and vim 8, there is a python process started taking 100% cpu whenever entering a vim file, also no errors are displayed

**Comment by w0rp** [comment] 2016-10-20 07:06
Do you see the problem when `g:ale_lint_on_enter` is set to `0`? Does it happen on all Vim files, or just some Vim files?

**Comment by bounceme** [comment] 2016-10-20 07:37
every .vim file,but not with that option at 0

**Comment by w0rp** [comment] 2016-10-20 08:57
I'll have to try this later with that version of Vint. It works on my machine.

**Comment by neersighted** [comment] 2016-10-20 12:43
I can't reproduce this on a mac or on linux with neovim. Have you tried reinstalling Vint from pip?

**Comment by bounceme** [comment] 2016-10-20 16:41
Vint works when using neomake, so I think it is a bug here. I did reinstall vint

**Comment by bounceme** [comment] 2016-10-20 17:19
I suspect the Ale#queue() function has to do with it

**Comment by sbdchd** [comment] 2016-10-22 16:49
This issue is occurring for me as well.

Initially there is only one vint instance created, but once I makes some edits, multiple processes are then created.

Setup:
- nvim 0.1.5
- OSX
- vint 0.3.9

<img width="600" alt="screenshot 2016-10-22 12 48 39" src="https://cloud.githubusercontent.com/assets/7340772/19620972/e3c28bd4-9855-11e6-90c8-8c7ee6db589f.png">


<img width="596" alt="screenshot 2016-10-22 12 28 33" src="https://cloud.githubusercontent.com/assets/7340772/19620849/3a19fd4e-9853-11e6-8e0d-95026238c76d.png">

**Comment by w0rp** [comment] 2017-02-15 23:07
@bounceme Many changes have happened since this issue was opened. Do you still see these issues?

**Comment by bounceme** [comment] 2017-02-15 23:24
I don't know, I can't check right now as my setup has been changed quite a bit too.

**Comment by sbdchd** [comment] 2017-02-16 00:08
I just tested with vint  and I am no longer experiencing this issue.

Setup:
- vint 0.3.10
- nvim 0.1.7
- OSX
- ale 8c758e3

**Comment by w0rp** [comment] 2017-02-16 19:35
Hmm. I'll close this for now, and the issue can be re-opened if it comes back.

**Closed by w0rp** 2017-02-16 19:35 UTC
Labels: bug
