### ISSUE TITLE
Vim scrolls up when I use my mouse

### ISSUE THREAD

**Issue by L3viathan** [w0rp/ale#1740] opened 2018-07-20 12:41 UTC
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 28 2018 16:29:16)
Included patches: 1-26

Operating System: Debian 8.10

### :ALEInfo

```
 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls', 'pyre']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = ['pylint']
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''flake8'' --version']
(executable check - failure) mypy
(executable check - success) pylint
(finished - exit code 1) ['/usr/bin/zsh', '-c', 'cd ''/home/jo'' && ''pylint''  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n ''/home/jo/test.py''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/usr/bin/zsh', '-c', 'cd ''/home/jo'' && ''flake8'' --format=default --stdin-display-name ''/home/jo/test.py'' - < ''/tmp/vwZ7SeA/5/test.py''']

<<<OUTPUT STARTS>>>
/home/jo/test.py:1:27: E999 SyntaxError: invalid syntax
/home/jo/test.py:39:1: E303 too many blank lines (4)
/home/jo/.local/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
<<<OUTPUT ENDS>>>
```

## What went wrong

Since updating ALE this morning, Vim constantly scrolls up whenever I move my mouse over the Vim window (running in tmux). When I set `mouse=`, this stops, but I like mouse support.

## Reproducing the bug

1. I updated ALE and all other plugins (using vim-plug; I've set it to autoload ALE only when I open a Python file)
2. I opened a Python file.
3. While my mouse moves, Vim scrolls up the file.

The problem stops when I disable ALE. The problem persists when I disable all other plugins.

Apart from the plugin itself, the only other line in my .vimrc referencing ale is `let g:ale_fixers = ['pylint']`. I notice from the ALEInfo output that ALE didn't seem to notice that (it also thinks flake8 and mypy are enabled).

**Comment by w0rp** [comment] 2018-07-20 14:24
>I notice from the ALEInfo output that ALE didn't seem to notice that (it also thinks flake8 and mypy are enabled).

You're reading it wrong.

> Enabled Linters: ['flake8', 'mypy', 'pylint']
> let g:ale_fixers = ['pylint']

This is a duplicate of #1631, you can leave your comments there.

**Closed by w0rp** 2018-07-20 14:24 UTC
