### ISSUE TITLE
Autocompletion - complete menu shows when typing - annoying

### ISSUE THREAD

**Issue by jellytux** [w0rp/ale#1896] opened 2018-09-07 23:47 UTC
Hi, when writing code the complete menu is shown while typing, I would like to trigger it with Ctrl-n and not have it show when typing. Is there an option for this?

**Comment by w0rp** [comment] 2018-09-09 10:28
Not yet. This is a duplicate of #1830.

The intention is to offer suggestions while you type which don't interrupt editing. I or someone else will add support for manually showing the completion menu later.

**Closed by w0rp** 2018-09-09 10:28 UTC
