### ISSUE TITLE
MacVim - Ale stopped working, still works in CLI

### ISSUE THREAD

**Issue by synic** [w0rp/ale#289] opened 2017-02-01 21:35 UTC
I installed Ale with NeoBundle, and it was working for a bit there.  Now it does not work at all (errors do not show up in the gutter).

I am using the same config and ale works in the CLI version of vim.

Is there anything obvious to check here?

Version information:
```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 25 2017 16:44:23)
MacOS X (unix) version
Included patches: 1-237
Compiled by travis@Traviss-Mac-592.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +channel         +comments        +diff            +extra_search    +fork()          +jumplist        +listcmds        +mouseshape      +mouse_urxvt     +odbeditor       +profile         +scrollbind      +tag_binary      +textobjects     +virtualedit     +windows         -xterm_clipboard
+arabic          +cindent         +conceal         +digraphs        +farsi           +fullscreen      +keymap          +localmap        +mouse_dec       +mouse_xterm     +packages        +python/dyn      +signs           +tag_old_static  +timers          +visual          +writebackup     -xterm_save
+autocmd         +clientserver    +cryptv          +dnd             +file_in_path    -gettext         +lambda          +lua/dyn         -mouse_gpm       +multi_byte      +path_extra      +python3/dyn     +smartindent     -tag_any_white   +title           +visualextra     -X11
+balloon_eval    +clipboard       +cscope          -ebcdic          +find_in_path    -hangul_input    +langmap         +menu            -mouse_jsbterm   +multi_lang      +perl/dyn        +quickfix        +startuptime     -tcl             +toolbar         +viminfo         -xfontset
+browse          +cmdline_compl   +cursorbind      +emacs_tags      +float           +iconv           +libcall         +mksession       +mouse_netterm   -mzscheme        +persistent_undo +reltime         +statusline      +termguicolors   +transparency    +vreplace        +xim
++builtin_terms  +cmdline_hist    +cursorshape     +eval            +folding         +insert_expand   +linebreak       +modify_fname    +mouse_sgr       +netbeans_intg   +postscript      +rightleft       -sun_workshop    +terminfo        +user_commands   +wildignore      -xpm
+byte_offset     +cmdline_info    +dialog_con_gui  +ex_extra        -footer          +job             +lispindent      +mouse           -mouse_sysmouse  +num64           +printer         +ruby/dyn        +syntax          +termresponse    +vertsplit       +wildmenu        -xsmp
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -f
ramework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE
```

**Comment by synic** [comment] 2017-02-01 21:42
Also, the errors are not showing up in the location list.  Is there any way to debug this or see any errors that might be occurring?

**Comment by w0rp** [comment] 2017-02-03 00:35
Which filetype are you testing with? Python files, etc.?

**Comment by synic** [comment] 2017-02-03 03:10
It is indeed Python

**Comment by ninjawithaneedle** [comment] 2017-02-03 13:19
Are you inside a virtualenv while in command line? If yes, it is possible that pylint is only installed for the virtualenv and not globally.

**Comment by synic** [comment] 2017-02-03 14:33
I am not currently using a virtualenv.

It seems to be related to python3.  I've got one project that is python 2, and Ale works there.  If I open python3 files in another project, Ale does not work there. 

`:ALEInfo` returns the following while editing the python3 file:

```

**Comment by w0rp** [comment] 2017-02-05 16:22
Hmm, what's your `flake8` version? It might be the newer `flake8` option messing things up again.

I think that linter should be modified to only use that flag if the flake8 version is new enough. Even if that's not your issue, I'll try and fix that soon enough.

**Comment by KarboniteKream** [comment] 2017-02-05 21:19
This might be unrelated, but I noticed that other plugins which are using the gutter (for instance `vim-signify`) stopped working as well, so this might be an issue with MacVim itself.

**Comment by w0rp** [comment] 2017-02-06 11:16
I just pushed some more complex code for the `flake8` linter now so it will support old flake8 versions again. Here is how it works.

1. A command chain is used, the first command checks if the version is stored in a cache for the given executable. If the version is found in the cache, then the command is skipped. If the version is not found in the cache, the executable will be run with `--version`. The executable name is used as the key for the cache.
2. The output from the previous command will be then used to determine the `flake8` command to run to check for errors. The cache for the versions will be checked again. If the version isn't in the cache, the version will be parsed from the output from the previous command.
3. If the version number, whether it was taken from the cache or not, is >= 3.0.0, then the `--stdin-display-name` flag will be included, otherwise it won't.

This should hopefully make the linter work better for everyone. Older versions should run again, and newer versions can automatically take advantage of the `--stdin-display-name` flag. For the vast majority of users, the `--version` command should only be run once per Vim session.

**Comment by synic** [comment] 2017-02-06 15:44
I updated, but unfortunately it hasn't helped.  

In MacVim, if I type `:!which flake8`, it shows `/usr/local/bin/flake8`, (in both the python2 and python3 projects) from brew.  The version is as follows:

```
[~]$ /usr/local/bin/flake8 --version
3.2.1 (pyflakes: 1.3.0, mccabe: 0.5.2, pycodestyle: 2.2.0) CPython 2.7.10 on Darwin
```

As a note, other gutter programs do still work in both projects.  `vim-gitgutter` remains visible.

**Comment by KarboniteKream** [comment] 2017-02-06 15:47
In my case, `ale` started working after this update. Can't say the same for `vim-gitgutter` and others.

**Comment by w0rp** [comment] 2017-02-06 17:34
It looks like I did fix the one issue. I don't know what's happen with MacVim at the moment.

I will note that there has been some trouble getting MacVim to work with the Vim 8 jobs feature at all in the past. See: #39. Nobody ever figured out how to fix that.

**Comment by w0rp** [comment] 2017-02-08 10:52
@synic Have recent changes fixed your issues here?

**Comment by synic** [comment] 2017-02-08 14:22
@w0rp unfortunately no.  Thanks for sticking with it, though!

**Comment by w0rp** [comment] 2017-02-08 21:30
Have you tried checking the version of `flake8` used for Vim in a terminal and Vim as a GUI? Maybe different paths are being used in each case. Do you see any error messages at all in MacVim?

I have seen some issues with MacVim in the past where Vim 8 jobs just don't seem to work at all.

**Comment by synic** [comment] 2017-02-08 21:32
`:!flake8 --version` and `:!which flake8` give the same responses in the terminal and in MacVim.

There are no error messages, and I don't see anything relevant in `:messages`.  Is there anywhere else I should look?

**Comment by w0rp** [comment] 2017-02-08 21:42
There is something else you could try. Could you try applying the patch I mentioned here? https://github.com/w0rp/ale/issues/283#issuecomment-278123151

I'm curious to see if some versions of MacVim will work better if the Vim 8 feature for sending a buffer directly to a job is replaced instead with manually sending the buffer through the channel commands.

**Comment by synic** [comment] 2017-02-08 22:16
No go (the patch doesn't apply cleanly to current master, but I think I edited it in correctly).

**Comment by w0rp** [comment] 2017-02-08 22:19
Hmm. Is there some previous revision of the plugin where it works for you? If you can get it working consistently with an old version, then we could look at the diff and find out what broke it for you.

**Comment by synic** [comment] 2017-02-08 22:23
I don't think it has ever worked, I think the title of this issue is misleading.  

It took me a bit to figure out that it wasn't that it *stopped* working, it just never worked, it just appeared that it stopped because it still works in the terminal, and still works in the python2 project.

I've tried it on another python3 project here (an opensource one if you want to try it) with the same result:  https://github.com/enderlabs/frf

**Comment by w0rp** [comment] 2017-02-08 22:32
Hmm, sounds like a MacVim issue then. Some users have reported some trouble in getting the plugin to work with MacVim at all. Unfortunately, no MacVim users with the problems have ever been dedicated enough to fix it. I don't typically have access to a Mac computer myself.

I'll try and see if I can somehow find someone with access to a Mac who is willing to track down an obscure Vim plugin bug.

**Comment by synic** [comment] 2017-02-08 22:56
Well, anything I can do, let me know.  Thanks!

**Comment by bwells** [comment] 2017-02-08 23:13
MacVim has been working just fine for me on both python2 and python3 projects. My vimrc is available in my [dotfiles](https://github.com/bwells/dotfiles/blob/master/.vimrc). I use a CWD based workflow and always launch both vim or mvim from the command line within the project folder.  MacVim is installed via homebrew. I checked and it works fine for me compiled with python2 support or python3 support (both at once is not supported). 

I use virtualenvs for everything and generally install pylint into the virtualenv.

If there's anything I can setup locally to attempt to reproduce an error I'm happy to help.

**Comment by synic** [comment] 2017-02-09 00:24
Started doing the process of elimination on my plugins, it seems like this one is the culprit somehow: https://github.com/mhinz/vim-startify

I'm still trying to figure out if I can find out why

**Comment by bwells** [comment] 2017-02-09 20:58
How are you installing MacVim and which version of python is compiled in (see `:version`)? As another theory I've seen pylint crash on certain files before. Can you pylint your python3 project from the command line manually?

**Comment by synic** [comment] 2017-02-10 15:30
I'm using flake8 instead of pylint.  My `:version` looks like this:

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  3 2017 16:49:50)
MacOS X (unix) version
Included patches: 1-297
Compiled by travis@Traviss-Mac-592.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +clientserver    +cursorbind      +ex_extra        +fullscreen      +langmap         +modify_fname    +mouse_urxvt     +path_extra      +reltime         +syntax          +timers          +viminfo         -xpm
+arabic          +clipboard       +cursorshape     +extra_search    -gettext         +libcall         +mouse           +mouse_xterm     +perl/dyn        +rightleft       +tag_binary      +title           +vreplace        -xsmp
+autocmd         +cmdline_compl   +dialog_con_gui  +farsi           -hangul_input    +linebreak       +mouseshape      +multi_byte      +persistent_undo +ruby/dyn        +tag_old_static  +toolbar         +wildignore      -xterm_clipboard
+balloon_eval    +cmdline_hist    +diff            +file_in_path    +iconv           +lispindent      +mouse_dec       +multi_lang      +postscript      +scrollbind      -tag_any_white   +transparency    +wildmenu        -xterm_save
+browse          +cmdline_info    +digraphs        +find_in_path    +insert_expand   +listcmds        -mouse_gpm       -mzscheme        +printer         +signs           -tcl             +user_commands   +windows
++builtin_terms  +comments        +dnd             +float           +job             +localmap        -mouse_jsbterm   +netbeans_intg   +profile         +smartindent     +termguicolors   +vertsplit       +writebackup
+byte_offset     +conceal         -ebcdic          +folding         +jumplist        +lua/dyn         +mouse_netterm   +num64           +python/dyn      +startuptime     +terminfo        +virtualedit     -X11
+channel         +cryptv          +emacs_tags      -footer          +keymap          +menu            +mouse_sgr       +odbeditor       +python3/dyn     +statusline      +termresponse    +visual          -xfontset
+cindent         +cscope          +eval            +fork()          +lambda          +mksession       -mouse_sysmouse  +packages        +quickfix        -sun_workshop    +textobjects     +visualextra     +xim
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/us
r/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE
```

... so I'm not really sure there.

Incidentally, the following settings make it work for both projects:

```
let g:ale_python_flake8_executable = 'python3'
let g:ale_python_flake8_args = '-m flake8'
```

Not entirely sure why :D

**Comment by w0rp** [comment] 2017-02-10 18:30
Hmm, looks like a configuration issue then. Perhaps `flake8` was running a different version of `flake8`?

**Comment by synic** [comment] 2017-02-10 18:32
I'm not totally sure.  It doesn't explain why it did work in the circumstances that it did, though.

**Comment by w0rp** [comment] 2017-02-11 22:21
If configuring the executable and the options fixes the issue for you, I'll consider this a configuration issue. Sometimes you need to use `python -m flake8` to use the right version of `flake8`.

**Closed by w0rp** 2017-02-11 22:21 UTC
Labels: bug
