### ISSUE TITLE
Nothing beign echo'ed when over error

### ISSUE THREAD

**Issue by FredrikAugust** [w0rp/ale#109] opened 2016-10-14 18:14 UTC
Hey, trying out ALE now, but it doesn't seem to echo errors nor highlight them when something is wrong. Using vim 8.0 1-22 with newest version of ALE (as of now). No errors or such, I am however using YCM if that could matter. I can post my config if you need, but it's only stuff from the readme.

**Comment by FredrikAugust** [comment] 2016-10-14 18:15
It appears that it is also spamming "No matching autocommands" now.. Strange

**Comment by w0rp** [comment] 2016-10-14 18:16
YouCompleteMe will likely conflict with this plugin.

I know about that other bug. I'll fix that right now.

**Comment by w0rp** [comment] 2016-10-14 18:18
If you pull again, that autocmd problem will be gone.

**Comment by FredrikAugust** [comment] 2016-10-14 18:18
Awesome! Do you know any workaround for the YCM thing?

**Comment by FredrikAugust** [comment] 2016-10-14 18:19
`[2016-10-14 20:19:16] > Error running :helptags /home/fredrik/.vim/bundle/ale/doc`

This might also be of interest to you; pops up every time I update.

**Comment by w0rp** [comment] 2016-10-14 18:20
https://github.com/Valloric/YouCompleteMe#the-gycm_echo_current_diagnostic-option

You might have to turn the similar option off in YCM.

**Comment by FredrikAugust** [comment] 2016-10-14 18:21
For some reason it still seems to spam bell sessions for me though. Weird :disappointed_relieved:

**Comment by w0rp** [comment] 2016-10-14 18:22
Someone might have to open a pull request for YouCompleteMe to add support for this plugin.

**Comment by hauleth** [comment] 2016-10-16 10:44
I also have no errors even despite that I am not using YCM.

**Comment by FredrikAugust** [comment] 2016-10-16 10:48
BTW my terminal is still pinging every time I unfocus it and it's on a line
where there is an error.

**Comment by hauleth** [comment] 2016-10-16 11:28
The same for me:

Setup:

- iTerm2
- NeoVim

The problem existed even when all plugins were disabled. So I believe that there is issue when using Ale with NeoVim.

**Comment by FredrikAugust** [comment] 2016-10-16 11:29
I'm using standard vim

**Comment by w0rp** [comment] 2016-10-16 14:38
I fixed the documentation issue.

What do you mean by "spamming bell sessions" and "pinging?" Could you paste some output?

**Comment by FredrikAugust** [comment] 2016-10-16 14:40
Hey, kind of busy right now, but I can do it later tonight. Basically; Konsole (KDE konsole) shows a little notification every time a bell signal is sent to the terminal and the terminal is not the focused window, and when I have my cursor over a line with an error it keeps on creating a new notification every appx. 1s

**Comment by w0rp** [comment] 2016-10-16 14:42
Maybe you need `:set noerrorbells` or `:set novisualbell`.

**Comment by FredrikAugust** [comment] 2016-10-16 14:43
I have :set noerrorbells in my vimrc

**Comment by FredrikAugust** [comment] 2016-10-16 14:43
I can try adding novisualbell now

**Comment by FredrikAugust** [comment] 2016-10-16 14:44
Nope, still receiving the error bell :confused:

**Comment by w0rp** [comment] 2016-10-16 14:46
I'm not sure what the issue is. If you could produce some kind of recording or some error output, that may help. The errors are just displayed with `echomsg`.

**Comment by hauleth** [comment] 2016-10-16 14:47
Setting `set belloff=all` resolves problem with bell, but still no error info.
--

Łukasz Niemier
lukasz@niemier.pl

**Comment by FredrikAugust** [comment] 2016-10-16 14:50
Thanks a lot @hauleth, that did indeed fix it.

**Comment by FredrikAugust** [comment] 2016-10-16 14:50
@w0rp How should I get the error output when the problem is the lack of output? Is there any log I can look in or such?

**Comment by w0rp** [comment] 2016-10-16 14:52
Do you see any signs in the sign column? Is the loclist being populated? Could you share your vimrc and version of Vim? Any information might help.

**Comment by hauleth** [comment] 2016-10-16 14:52
You can use `:lwindow` or `:lopen` to show location list. But problem still exist as I would rather see it inline.
--

Łukasz Niemier
lukasz@niemier.pl

**Comment by FredrikAugust** [comment] 2016-10-16 14:54
I'm using a plugin to show the loclist, and I can confirm that it's being populated. I also get signs in the column.

http://i.imgur.com/xGBNRll.png

**Comment by FredrikAugust** [comment] 2016-10-16 14:55
!! is error, while -- is warning.

**Comment by hauleth** [comment] 2016-10-16 14:56
You can see issue there: https://asciinema.org/a/668m24qyvev4aieq04aa1u5dl

My NeoVim version:

```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/build/config -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/src -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160822-30240-1vpbim8/neovim-0.1.5/build/include
Skompilowany przez hauleth@niuniobook

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

       vimrc systemu: "$VIM/sysinit.vim"
   odwet dla $VIM-a: "/usr/local/Cellar/neovim/0.1.5/share/nvim"
```

**Comment by FredrikAugust** [comment] 2016-10-16 14:57
I'm having the exact same issue as @hauleth showed here. Everything is working except for the echo part.

**Comment by w0rp** [comment] 2016-10-16 15:01
What do you see if you try this?

```vim
setlocal shortmess+=T
let x = 'hello' 
exec "norm :echomsg x\n" 
```

Does it print "hello"?

**Comment by hauleth** [comment] 2016-10-16 15:04
@w0rp no. But when I execute simply `echomsg z` then everything works. I do not know why have that additional level of indirection.

**Comment by FredrikAugust** [comment] 2016-10-16 15:05
The example worked for me, though I had to change : to ; as I have remapped those in my config.

**Comment by w0rp** [comment] 2016-10-16 15:06
`norm` is used because it's required for truncating messages. See here. http://vim.wikia.com/wiki/Get_shortened_messages_from_using_echomsg

**Comment by FredrikAugust** [comment] 2016-10-16 15:07
Aaah, can you add an option so I can change it from using : to using ;?

**Comment by hauleth** [comment] 2016-10-16 15:07
@FredrikAugust that could be issue, there should be call to `norm!` instead of `norm` as the following would use mappings, and first one forces to use default Vim.

**Comment by w0rp** [comment] 2016-10-16 15:08
That makes sense. I'll change that.

**Comment by FredrikAugust** [comment] 2016-10-16 15:08
Great!

**Comment by w0rp** [comment] 2016-10-16 15:09
Right, give that a go.

**Comment by FredrikAugust** [comment] 2016-10-16 15:09
Alright, one moment please.

**Comment by FredrikAugust** [comment] 2016-10-16 15:10
Great, it works perfectly now! :)

**Comment by w0rp** [comment] 2016-10-16 15:11
Nice. Does it work fro you, @hauleth?

**Comment by hauleth** [comment] 2016-10-16 15:12
Works. But I have local copy of the Ale because I have added extra linters that I use in my work #113 so it need to wait a little :P

**Comment by w0rp** [comment] 2016-10-16 15:13
I'll have a look at that pull request, and we can get that merged soon enough.

**Closed** 2016-10-16 15:12 UTC
Labels: bug

**Comment by w0rp** [comment] 2016-10-16 15:13
Thanks for the info! You get weird errors on different setups for different people in Vim, and can be hard to figure out why something works for 80% of people, but not the other 20%.

**Comment by hauleth** [comment] 2016-10-16 15:14
@w0rp and this is only first day of using Ale :D

**Comment by FredrikAugust** [comment] 2016-10-16 15:42
Only used it for a couple of days myself, seems great so far :)
