### ISSUE TITLE
 g:ale_lint_on_enter is not respected

### ISSUE THREAD

**Issue by smhc** [w0rp/ale#1707] opened 2018-07-09 07:23 UTC
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun  7 2018 10:26:29)
Included patches: 1-37

Operating System: 

Linux

### :ALEInfo

 Current Filetype:
Available Linters: []
  Enabled Linters: []
 Suggested Fixers:
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'perl': ['perl']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = v:null
let g:ale_list_vertical = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 0
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = '►'
let g:ale_sign_info = 'i'
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = '»'
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1

Setting 'let g:ale_lint_on_enter=0' does not have any effect, it is always set to 1 in ale#events#Init()
This is because ale#events#Init() is called before the user setting for g:ale_lint_on_enter is set, thus the event listener is set up regardless. The event listener could re-check the 'ale_lint_on_enter' setting, which is what s:LintOnEnter does. Or ale#events#Init should be deferred until the users settings are read.

A work around is to use the following in .vimrc:

" ALE options
let g:ale_lint_on_enter=0
let g:ale_lint_on_filetype_changed=0
" Workaround to get ALE to re-read settings
:ALEToggle
:ALEToggle

See also this issue: https://github.com/w0rp/ale/issues/1619

1. let g:ale_lint_on_enter=0
2. ALE linted on enter

**Comment by w0rp** [comment] 2018-07-09 07:56
Set the variable in your vimrc file before ALE is loaded, like the documentation says.

**Comment by smhc** [comment] 2018-07-09 10:20
Thanks, I set it before 'packloadall' and that seems to fix it. 

Although I disagree the documentation says this, or at least very clearly. The doc for g:ale_lint_on_enter has:

```
  g:ale_lint_on_enter                                       g:ale_lint_on_enter

    Type: Number
    Default: 1

    When this option is set to 1, the BufWinEnter and BufRead events will
    be used to apply linters when buffers are first opened. If this is not
    desired, this variable can be set to 0 in your vimrc file to disable this
    behaviour.

    The FileChangedShellPost and BufEnter events will be used to check if
    files have been changed outside of Vim. If a file is changed outside of
    Vim, it will be checked when it is next opened.

    A BufWinLeave event will be used to look for the E924, E925, or E926
    errors after moving from a loclist or quickfix window to a new buffer. If
    prompts for these errors are opened after moving to new buffers, then ALE
    will automatically send the <CR> key needed to close the prompt.
```

I searched the doc for 'before' and 'vimrc' and saw a few mentions:

g:ale_pattern_options_enabled:
...  as long as the setting is configured before ALE is loaded.

 g:ale_use_global_executables 
...  This option must be set before ALE is loaded, preferably in a vimrc file.

The only reference to 'packloadall' suggests that it should be loaded prior to configuring an ale linter:
"Linters can be defined from vimrc and other files as long as this function is loaded first."



The main README has:

```
" Put these lines at the very end of your vimrc file.

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
```

which is in direct contradiction.

**Comment by w0rp** [comment] 2018-07-15 20:40
Duplicate of #1619.

**Closed by w0rp** 2018-07-15 20:40 UTC
