### ISSUE TITLE
echo message hides cursor

### ISSUE THREAD

**Issue by graingert** [w0rp/ale#1536] opened 2018-04-27 10:15 UTC
https://asciinema.org/a/wCdTTG4PBBczg1KQpbc1SJsie

## Information

**VIM version**

PASTE JUST THE FIRST TWO LINES OF `:version` HERE.
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
```

Operating System: WHAT OS WERE YOU USING?

Ubuntu 18.04

### :ALEInfo

PASTE OUTPUT OF `:ALEInfo` HERE. YOU CAN TRY `:ALEInfoToClipboard`.
```

 Current Filetype: python
Available Linters: ['flake8', 'mypy', 'prospector', 'pycodestyle', 'pyflakes', 'pylint', 'pyls']
  Enabled Linters: ['flake8', 'mypy', 'pylint']
 Linter Variables:

let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_mypy_executable = 'mypy'
let g:ale_python_mypy_ignore_invalid_syntax = 0
let g:ale_python_mypy_options = ''
let g:ale_python_mypy_use_global = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '✗'
let g:ale_sign_info = '⚠'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '✗'
let g:ale_sign_style_warning = '⚠'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /home/graingert/projects/sqlalchemy-redshift/.tox/lint/bin/flake8
(started) ['/usr/bin/zsh', '-c', '''/home/graingert/projects/sqlalchemy-redshift/.tox/lint/bin/flake8'' --version']
(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''/home/graingert/projects/sqlalchemy-redshift/.tox/lint/bin/flake8'' --version']
(executable check - failure) mypy
(executable check - failure) pylint
(finished - exit code 0) ['/usr/bin/zsh', '-c', '''/home/graingert/projects/sqlalchemy-redshift/.tox/lint/bin/flake8'' --format=default - < ''/tmp/vKvJpaM/1/__init__.py''']

<<<NO OUTPUT RETURNED>>>
```

## What went wrong

echo message hides cursor

## Reproducing the bug

https://asciinema.org/a/wCdTTG4PBBczg1KQpbc1SJsie

Steps for repeating the bug:

1. run vim with ale on Ubuntu 18.04 with this https://github.com/graingert/vimrc
2. introduce an error
3. move cursor to errant line
4. observe as cursor disappears (or moves to the echo message)

**Comment by w0rp** [comment] 2018-04-27 18:32
I believe this is a bug in Vim, introduced in a somewhat recent patch, and fixed in a patch after that. I don't see this problem myself, but I have met someone who did.

**Comment by w0rp** [comment] 2018-04-27 18:38
https://github.com/vim/vim/commit/acda04f5c641330cd589ca52eb61d1ab0d62385f I think this might be the commit which fixes that bug. Can you try this again with a newer version of Vim?

**Comment by w0rp** [comment] 2018-04-27 18:39
I think it was broken here: https://github.com/vim/vim/commit/a338adcf222b6a24e26ea5ae6a2ad27f914acb38?diff=split#diff-ceb2e2231c5d45523135ca0cfc492792L470

I found this thread. https://github.com/vim/vim/issues/2612

**Comment by graingert** [comment] 2018-04-27 22:11
Dang, will have a look at a newer Vim PPA.

If so I'll raise an Ubuntu error

**Comment by laerus** [comment] 2018-04-30 12:16
hello, i can confirm this behavior in debian testing with 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 05 2018 16:15:22)
Included patches: 1-1453
```

**Comment by laerus** [comment] 2018-04-30 12:51
The problem disappears one of the latest releases i.e `v8.0.1775`

**Comment by w0rp** [comment] 2018-04-30 14:05
Okay, thanks to everyone for the information. That confirms my suspicions then. We'll have to ask Debian/Ubuntu package maintainers to update the packages. It's rather annoying that the version of Vim you install in the latest and greatest version of Ubuntu contains a bug which makes ALE annoying to use.

**Comment by graingert** [comment] 2018-04-30 14:36
If anyone has Ubuntu can you mark the issue https://bugs.launchpad.net/ubuntu/+source/vim/+bug/1768026 as affecting you, please?

**Comment by frioux** [comment] 2018-05-11 18:34
Here's a PPA that fixed it for me in 18.04.

**Comment by graingert** [comment] 2018-05-11 19:06
Where?

**Comment by frioux** [comment] 2018-05-11 20:13
@graingert I updated the original post; use web view.

**Comment by w0rp** [comment] 2018-05-16 20:39
I think I've used that PPA before myself, so that's probably a good replacement until the fix lands in the main Ubuntu repo.

**Comment by graingert** [comment] 2018-05-16 20:40
I'm using that PPA now: changed my life

**Comment by w0rp** [comment] 2018-06-20 11:04
Okay. The Ubuntu package maintainers need to fix their broken package. That's how this ought to be fixed.

**Comment by jefft** [comment] 2018-06-27 06:47
Thanks @fhpraw for the hint. The problem is with the `vim-gtk` package, not `vim`.

Rather than uninstalling `vim-gtk`, one can run `sudo update-alternatives --config vim`, and configure vim to use `/usr/bin/vim.basic` instead of `/usr/bin/vim.gtk`.

**Comment by w0rp** [comment] 2018-07-17 10:24
I'll close this issue, because it's a Vim bug, not an ALE bug.

**Closed by w0rp** 2018-07-17 10:24 UTC
Labels: triage

**Comment by vcavallo** [comment] 2019-11-07 22:14
> Another solution, **for who usually run vim on terminal emulator and doesn't need gvim**. I don't know why, but **by removing vim-gtk and vim-gui-common has solved this problem.**
> 
> ```shell
> sudo apt remove vim-gtk vim-gui-common
> ```
> 
> **tested on xubuntu 18.04 amd64**
> no need to add another unofficial PPA to your system.

Echoing what @frioux said - if you remove `vim-gtk` you will compromise your ability to use the shared clipboard registers! proceed with caution.
