### ISSUE TITLE
Unknown function: ale_linters#typescript#tsserver#GetExecutable

### ISSUE THREAD

**Issue by croaky** [w0rp/ale#1782] opened 2018-08-03 16:18 UTC
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 22 2018 05:24:30)
macOS version

Operating System: macOS High Sierra

### :ALEInfo

```
 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['tslint', 'tsserver']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {}
let b:ale_fixers = ['prettier']
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = ['tslint', 'tsserver']
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /Users/croaky/project/node_modules/.bin/tslint
(finished - exit code 2) ['/usr/local/bin/zsh', '-c', 'cd ''/Users/croaky/project/src/state'' && ''/Users/croaky/project/node_modules/.bin/tslint'' --format json -c ''/Users/croaky/project/tslint.json'' ''/var/folders/mm/01539mv97sscp3mq__ftqysw0000gn/T/vY9hrAQ/2/lifecycle.test.ts''']

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":48,"line":11,"position":430},"failure":"unused expression, expected an assignment or function call","name":"../../../../../../../../var/folders/mm/01539mv97sscp3mq__ftqysw0000gn/T/vY9hrAQ/2/lifecycle.test.ts","ruleName":"no-unused-expression","ruleSeverity":"ERROR","startPosition":{"character":47,"line":11,"position":429}}]
<<<OUTPUT ENDS>>>

(finished - exit code 2) ['/usr/local/bin/zsh', '-c', 'cd ''/Users/croaky/project/src/state'' && ''/Users/croaky/project/node_modules/.bin/tslint'' --format json -c ''/Users/croaky/project/tslint.json'' ''/var/folders/mm/01539mv97sscp3mq__ftqysw0000gn/T/vY9hrAQ/3/lifecycle.test.ts''']

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":48,"line":11,"position":430},"failure":"unused expression, expected an assignment or function call","name":"../../../../../../../../var/folders/mm/01539mv97sscp3mq__ftqysw0000gn/T/vY9hrAQ/3/lifecycle.test.ts","ruleName":"no-unused-expression","ruleSeverity":"ERROR","startPosition":{"character":47,"line":11,"position":429}}]
<<<OUTPUT ENDS>>>
```

## What went wrong

```
Error detected while processing function ale#events#LintOnEnter[5]..ale#Queue[49]..ale#Lint[34]..ale#engine#RunLinters[14]..<SNR>70_RunLinter[2]..ale#lsp_linter#CheckWith
LSP[2]..ale#lsp_linter#StartLSP[23]..ale#linter#GetCommand:
line    1:
E117: Unknown function: ale_linters#typescript#tsserver#GetExecutable
E15: Invalid expression: has_key(a:linter, 'command_callback')   ? ale#util#GetFunction(a:linter.command_callback)(a:buffer)   : a:linter.command
```

## Reproducing the bug

I opened a TypeScript file after updating to latest `master`.

I was able to fix the bug by rolling back to 9ef266d0. It seems like the issue was introduced in 21728436.

**Comment by killtheliterate** [comment] 2018-08-03 16:21
same. https://github.com/w0rp/ale/issues/1781

**Comment by w0rp** [comment] 2018-08-03 16:31
Duplicate of the other issue.  I have fixed that now.

**Closed by w0rp** 2018-08-03 16:31 UTC

**Comment by croaky** [comment] 2018-08-03 17:38
Thanks!
