### ISSUE TITLE
Feature request: the ability to toggle whether or not ALE is on.

### ISSUE THREAD

**Issue by Soares** [w0rp/ale#189] opened 2016-11-25 21:35 UTC
Sometimes I have a file where I just don't care about warnings, and I want some way to say "be quiet, ALE." I couldn't find any functionality of  this form mentioned in the docs.

**Comment by abalmos** [comment] 2016-11-26 06:21
I agree. I find myself completely disabling ale (and then forgetting to re-enable it afterward) when working projects that do not care about linting.

**Comment by abalmos** [comment] 2016-11-26 06:22
This seems to be a duplicate of #122

**Comment by w0rp** [comment] 2016-11-28 09:35
Yeah, this is a duplicate. I'll close this issue.

**Closed** 2016-11-28 09:35 UTC
Labels: duplicate
