### ISSUE TITLE
[ale-cpp

### ISSUE THREAD

**Issue by eichf** [w0rp/ale#1686] opened 2018-06-28 18:34 UTC
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 17, compiled May 31 2018 20:13:20)
Included patches: 1-26

Operating System: Void Linux, Kernel 4.16.14_1

### :ALEInfo

```
 Current Filetype: cpp
Available Linters: ['clang', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'cquery', 'flawfinder', 'gcc']
   Linter Aliases:
'gcc' -> ['g++']
  Enabled Linters: ['clang', 'clangtidy']
 Suggested Fixers: 
  'clang-format' - Fix C/C++ files with clang-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_cpp_clang_executable = 'clang++'
let g:ale_cpp_clang_options = '-std=c++14 -Wall'
let g:ale_cpp_clangtidy_checks = ['*']
let g:ale_cpp_clangtidy_executable = 'clang-tidy'
let g:ale_cpp_clangtidy_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'cpp': ['clang', 'clangtidy']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) clang++
(started) ['/bin/zsh', '-c', '''clang++'' -S -x c++ -fsyntax-only -iquote ''/home/flrn/workbench/eich18/software/vimeTK/src'' -std=c++14 -Wall - < ''/tmp/vC3Pxln/1/core.cc''']
(executable check - success) clang-tidy
(started) ['/bin/zsh', '-c', '''clang-tidy'' -checks=''*'' ''/home/flrn/workbench/eich18/software/vimeTK/src/core.cc'' -p ''/home/flrn/workbench/eich18/software/vimeTK/build''']
(finished - exit code 1) ['/bin/zsh', '-c', '''clang++'' -S -x c++ -fsyntax-only -iquote ''/home/flrn/workbench/eich18/software/vimeTK/src'' -std=c++14 -Wall - < ''/tmp/vC3Pxln/2/core.cc''']

<<<OUTPUT STARTS>>>
<stdin>:37:10: fatal error: 'docopt.h' file not found
#include "docopt.h"
         ^~~~~~~~~~
1 error generated.
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/bin/zsh', '-c', '''clang-tidy'' -checks=''*'' ''/home/flrn/workbench/eich18/software/vimeTK/src/core.cc'' -p ''/home/flrn/workbench/eich18/software/vimeTK/build''']

<<<OUTPUT STARTS>>>
[some more clang-tidy output here]
<<<OUTPUT ENDS>>>
```

## What went wrong

`g:ale_c_build_dirs` should be populated and the `compile_commands.json` should be retrieved from there. This is not the case, neither by default nor if I manually specify that variable to contain something meaningful.

I am guessing without that variable correctly set, ale is not able to find the `compile_commands.json` file and is therefore not using it.

## Reproducing the bug

1. Install ale.
2. Put the following in `.vimrc` [optional, bug shows up no matter what]
```vim
let g:ale_linters = { 'cpp': ['clang', 'clangtidy'] }
let g:ale_c_build_dir_names = ['build', 'release']
```
3. Start vim from root directory of project with `build` directory containing CMake generated build information, including `compile_commands.json`.

I fully realise this is likely my own fault, however I can't seem to get it working. Sorry for spamming the issue tracker.

**Comment by gdmsl** [comment] 2018-08-07 16:39
I have the same problem. I set in my config file:

~~~vim
" Ale {{{
augroup ale_config
    autocmd!
    let g:ale_c_parse_compile_commands = 1
    let g:ale_linters = { 'cpp': ['clangtidy'] }
    let g:ale_c_build_dir_names = ['build', 'release', 'debug']
augroup END
" }}}
~~~

But looking at ALEinfo no build directory is passed to clang-tidy

~~~
(finished - exit code 0) ['/bin/zsh', '-c', '''clang-tidy'' -checks=''*'' ''/someabsolutepath/configuration.hpp''']
~~~

**Comment by w0rp** [comment] 2018-08-07 20:07
Could you let me know what your directory structure looks like? Where is `compile_commands.json` in your project, and where is the file you opened?

**Comment by gdmsl** [comment] 2018-08-08 08:04
Yes, of course. Here is an extract of the `tree` inside the project folder

```
.
├── build
│   ├── applications
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   ├── cmake_install.cmake
│   ├── compile_commands.json
│   ├── config
│   ├── configuration.plist
│   ├── CTestTestfile.cmake
│   ├── libs
│   ├── Makefile
│   ├── test
│   └── yaml-cpp.pc
├── CMakeLists.txt
├── config
├── include
│   └── mylib
│       └── configuration.hpp
├── libs
├── README.md
├── src
│   └── configuration.cpp
├── tags
├── templates
└── test
```

the file I opened is in include/mylib/configuration.hpp

**Comment by w0rp** [comment] 2018-08-08 08:17
Ah, it's a header file. Someone added some code a while ago to exclude setting the project directory for header files, because that apparently caused issues. Does it work in newer versions of `clangtidy`?

**Comment by gdmsl** [comment] 2018-08-08 08:32
Oh. OK, now I see the problem :(

This will not work for me because in the same directory there are only header files. I think I will need to use custom vim options per project and pass the right options to clang-tidy.

Maybe you can have the linter to read options for clang reading a `.clang_complete` file in the project (current nvim) directory but this is more a feature request.

Thank you.

**Comment by w0rp** [comment] 2018-08-08 08:52
This is a duplicate of  #782.

**Closed by w0rp** 2018-08-08 08:52 UTC
Labels: triage

**Comment by ManuelMeraz** [comment] 2018-11-02 21:43
> The general problem is that headers aren't translation units, and aren't included in `compile_commands.json`, so no flags are set for them. I added some code recently for taking compilation flags out of `compile_commands.json` and using them for `gcc` and `clang`, which is off by default, and what I did for header files was just look for the flags of any other file in the same directory. I don't know if `clangtidy` does something similar now.

How do I turn this on?
