### ISSUE TITLE
Disable auto completion menu by set ale_completion_delay to -1

### ISSUE THREAD

**Issue by axpira** [w0rp/ale#2454] opened 2019-04-24 19:29 UTC
It's possible to add -1 as possible value on ale_completion_delay to disable auto popup menu?

With this can use only manual completion on press <c-x> <c-o>

**Comment by w0rp** [comment] 2019-04-24 21:39
You can just set `g:ale_completion_enabled` to `0`, and use manual completion without enabling automatic completion.

**Comment by axpira** [comment] 2019-04-24 23:42
But the ominifunc is set with` g:ale_completion_enabled` to `0` ?
Because I want to keep using `<c-x><c-o>` to complete

**Comment by w0rp** [comment] 2019-04-25 10:09
Is your issue that the temporary modification to `omnifunc` isn't reset after manually requesting completions? I can fix that.

**Comment by axpira** [comment] 2019-04-25 14:02
When I keep `let g:ale_completion_enabled = 0` and try to press `<c-x><c-o>` I received:
`E764: Option 'omnifinc' is not set`

**Comment by w0rp** [comment] 2019-04-25 15:14
There's no omnifunc function available for ALE's completion. This is a duplicate of #2285 then.

**Closed by w0rp** 2019-04-25 15:14 UTC
Labels: triage
