### ISSUE TITLE
Add support for Haskell IDE Engine (aka hie)

### ISSUE THREAD

**Issue by unode** [w0rp/ale#1578] opened 2018-05-13 17:27 UTC
[Haskell IDE Engine](https://github.com/haskell/haskell-ide-engine) is a server implementing Language Server Protocol.

It encapsulates [most of the linters currently supported by ALE](https://github.com/haskell/haskell-ide-engine/blob/master/docs/Tools.md) in a unified interface simplifying use and providing somewhat better management of system resources.

**Comment by Saul-Mirone** [comment] 2018-07-10 03:04
+1, since ghc-mod is not maintained anymore, HIE is really important.

**Comment by alex404** [comment] 2018-07-18 14:45
I'm also eagerly waiting for this.

**Comment by w0rp** [comment] 2018-07-18 14:55
Go ahead and create a pull request for it if you know how to start the server. Have a look at existing linters in the `ale_linters` directory and `:help ale#linter#Define()` for a description of how that works.

**Comment by alex404** [comment] 2018-07-18 14:58
Thanks for the tips. I'll look into it and give it a shot.

**Comment by Luxed** [comment] 2018-07-19 15:07
@alex404 
I'm working on that right now, here is the branch:
https://github.com/Luxed/ale/tree/hie
I don't think it's ready to be a PR yet, but it works pretty much as intended.
Simply enable the `hie` linter for haskell and you're good to go !
( I basically ripped off the Rust rls code to use for the HIE one)
I'll make a PR later today.

**Comment by w0rp** [comment] 2018-07-19 15:10
Sounds good to me. :+1:

**Comment by Luxed** [comment] 2018-08-02 19:30
@alex404 @Saul-Mirone , PR has been merged ! Please go ahead and test it to see if it is working correctly.
It worked for me, but I'm a begginer so I don't work on any real codebase, just a simple stack project.
Everything should work as intended as long as you have `hie` in your path. Then it searches for the stack file, the cabal file and it will use the current directory as a default to work on "plain GHC projects".

**Comment by alex404** [comment] 2018-08-02 20:43
Seems to work well so far! Thanks for your hard work! I'll report if any problems come up.

**Closed** 2018-08-02 20:47 UTC
Labels: LSP, new linter
