### ISSUE TITLE
Linting for the Nix language not working.

### ISSUE THREAD

**Issue by LeOtaku** [w0rp/ale#1454] opened 2018-03-27 18:02 UTC
## Information

**VIM version**
NVIM v0.2.2
Build type: Release

Operating System: 
NixOS 18.09.git.56fb68dcef4 (Jellyfish)

### :ALEInfo
Current Filetype: nix
Available Linters: ['nix']
  Enabled Linters: ['nix']
 Linter Variables:
 Global Variables:
let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
(executable check - success) nix-instantiate
(started) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''/tmp/nvimA7U0lI
/2/leovim.nix''']
(finished - exit code 0) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/3/leovim.nix''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 0) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/4/leovim.nix''']
<<<NO OUTPUT RETURNED>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/5/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $end, at ^[[1m(string)^[[0m:38:2
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/6/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $end, at ^[[1m(string)^[[0m:38:2
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/7/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/8/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/9/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/10/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/11/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/12/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/13/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>
(finished - exit code 1) ['/run/current-system/sw/bin/zsh', '-c', 'nix-instantiate --parse - < ''
/tmp/nvimA7U0lI/14/leovim.nix''']
<<<OUTPUT STARTS>>>
^[[31;1merror:^[[0m syntax error, unexpected $undefined, at ^[[1m(string)^[[0m:2:3
<<<OUTPUT ENDS>>>

## What went wrong

When using ALE with files written in the Nix language, no errors/warnings are displayed. ALEInfo shows that errors are being returned from nix-instantiate. Other filetypes seem to work just fine.

## Reproducing the bug 

Steps for repeating the bug:

Install Neovim with the ALE plugin using the Nix utilities ([Wiki entry](https://nixos.wiki/wiki/Vim_plugins)) (this might not be relevant)
open a .nix file
write some incorrect code
`ALEInfo` shows that it finds the errors, but they are not displayed.

**Comment by w0rp** [comment] 2018-04-05 11:46
That definitely looks like a color code issue to me. I wouldn't be surprised if `nix` has `--no-color` option, or similar.

**Comment by w0rp** [comment] 2018-04-05 11:54
I raised an issue on what looks like their GitHub project asking if someone knows how to disable color output for `nix-instantiate`. Maybe I'll get a response there.

**Comment by w0rp** [comment] 2018-04-05 13:39
I turns out this is actually a regression in `nix`. Try updating to a newer version of `nix-instantiate` once it's out. I'll keep this open for now, because it might be worth removing color codes from output automatically too.

**Comment by LeOtaku** [comment] 2018-04-06 15:34
Ok, that sounds great! Is there an easy way to change the command ALE runs to get error feedback? `nix-instantiate` comes bundled with Nix and I would rather not risk switching to a potentially broken git version for that. Writing a simple wrapper command seems "safer".

**Comment by w0rp** [comment] 2018-04-06 18:02
There's no support for changing the executable for the linter at the moment. You could set up `PATH` with a different `nix-instantiate` executable without this problem.

**Comment by LeOtaku** [comment] 2018-06-17 23:05
I can confirm that linting now perfectly works (and has been working for quite some time) using the `nixos-unstable` branch. Do you want (me) to close this issue now?

**Comment by w0rp** [comment] 2018-06-17 23:09
Sure, I'll close it now. Thank you for the update.

**Closed by w0rp** 2018-06-17 23:09 UTC
Labels: bug
