### ISSUE TITLE
Option to add preprocessors to some linters

### ISSUE THREAD

**Issue by languitar** [w0rp/ale#1231] opened 2017-12-17 14:00 UTC
Currently, I am mostly writing LaTeX documents, which contain a lot of custom markup that prevents certain text linters from wroking correctly. I could easily provide a script to remove some of the markup (detex, custom script etc) so that these linters would provide much better results. It would be nice if there was some global way to configure such preprocessing per linter without having to touch all linter definitions.

**Comment by languitar** [comment] 2017-12-19 13:24
I think I have found a partially nice solution: I just redefined the linter in my `.exrc` file for the project, for instance like this:

```latex
call ale#linter#Define('tex', {
\   'name': 'vale',
\   'executable': 'vale',
\   'command': 'cat %t | ' . getcwd() . '/detex.py | vale --output=JSON',
\   'callback': 'ale#handlers#vale#Handle',
\})
```

**Comment by w0rp** [comment] 2017-12-20 10:59
I'll say this is a duplicate of #1115.

**Closed by w0rp** 2017-12-20 10:59 UTC
Labels: triage

**Comment by languitar** [comment] 2018-01-11 13:07
@w0rp I just noticed that this resets / removes all default linters for the file type. Any chance to get around this?

**Comment by w0rp** [comment] 2018-01-11 14:43
What does?

**Comment by languitar** [comment] 2018-01-11 14:48
Calling `ale#linter#Define` in the `.exrc` file resets the available default linters. So I only have the linters explicitly defined like that in the `.exrc` file available then.

**Comment by languitar** [comment] 2018-01-11 14:55
My suspicion is the following:
```vim
function! ale#linter#GetAll(filetypes) abort
    let l:combined_linters = []

    for l:filetype in a:filetypes
        " Load linter defintions from files if we haven't loaded them yet.
        if !has_key(s:linters, l:filetype)
            execute 'silent! runtime! ale_linters/' . l:filetype . '/*.vim'
```
I have already defined `s:linters` through the calls in `.exrc`. Therefore, the default linters will never be loaded.

**Comment by w0rp** [comment] 2018-01-11 17:25
Defining linters outside of an `ale_linters` directory isn't supported, but I but it wouldn't be too much effort to support it by using a second Dictionary for preventing the runtime line from being run many times. I'll open an issue for that.

**Comment by languitar** [comment] 2018-01-11 17:27
Great, I could get around this by manually executing
```vim
execute 'silent! runtime! ale_linters/' . l:filetype . '/*.vim'
```
in my `.exrc`. But that's a bad hack.

**Comment by w0rp** [comment] 2018-01-11 17:29
Here's the issue for that: #1278
