### ISSUE TITLE
Using SpellBad and SpellCap to highlight errors and warnings

### ISSUE THREAD

**Issue by aliev** [w0rp/ale#310] opened 2017-02-07 07:46 UTC
Is it possible to do that? For syntastic: https://github.com/vim-syntastic/syntastic/blob/master/doc/syntastic.txt#L225

**Comment by dflupu** [comment] 2017-02-07 13:18
Try
```
highlight link ALEErrorSign SpellBad
highlight link ALEWarningSign SpellCap
```

**Comment by aliev** [comment] 2017-02-07 13:58
@dflupu does not work for me. I would like to disable signs and enable only spell bad or spell cap highlighting

**Comment by w0rp** [comment] 2017-02-07 21:22
I plan on implementing this eventually. If someone else wants to implement it, go for it.

In order to implement it, you need to set up some special highlights which indicate the lines and columns for mistakes.

I'll close this issue, as it's a duplicate of #171

**Closed by w0rp** 2017-02-07 21:22 UTC
