### ISSUE TITLE
Go build linter doesn't work

### ISSUE THREAD

**Issue by DiscoViking** [w0rp/ale#234] opened 2016-12-28 12:48 UTC
During #180 it was discussed that go build can't work properly unless you copy across all the go files in the package.

This was seemingly then forgotten and the PR merged without it being addressed.

As it is,  the go build linter doesn't work for packages with more than 1 file.
It also doesn't work for test files,  since the go build command ignores them.

**Comment by DiscoViking** [comment] 2016-12-28 15:33
The annoying problem here is that the go compiler won't let you compile a package out of files which are in different directories.  Otherwise we could just pass it in all the existing files in the package as well as the current one.

Logically there are only two ways to handle this:

1. Copy all the other files from the package into the temp directory.
2. Use a file in the package directory as the temporary file instead of a temp dir.
(3. Somehow get go build to allow files in multiple directories)

(1) Has some design problems around how you specify how to pass those copied files into the build tool.
(2) Has potential file clash issues.  (the idea would be to use something like `.ale.<filename>`.  Which then doesn't work if two people open the same file at once (but then should people expect that to work?  swapfiles etc)

But then again,  this feels like a fairly go specific problem,  I don't know any other languages that care which directory your files are in to the same extent.  Feels like a bit of a waste to build extra infrastructure just for it.

**Comment by fwip** [comment] 2016-12-31 01:31
I think you can just supply the files as arguments to the `go build` command.
```
% go build -h
usage: build [-o output] [-i] [build flags] [packages]

Build compiles the packages named by the import paths,
along with their dependencies, but it does not install the results.

If the arguments to build are a list of .go files, build treats
them as a list of source files specifying a single package.
```

**Comment by DiscoViking** [comment] 2016-12-31 09:08
Unfortunately this doesn't work because go build requires all your files to be in the same directory. 
I'm messing around seeing if I can do something by calling go tool compile directly, but its proving difficult.

**Comment by w0rp** [comment] 2017-01-04 13:02
Is there no way to specify import paths? That's how it works with most languages. I don't use Go myself. If anyone is familiar with Go and knows how to get this to work, open a pull request.

**Comment by jamesruan** [comment] 2017-01-23 03:39
So is this PR solves linting multiple files of the same package?
It is quite common to write multiple files for a package.

**Comment by DiscoViking** [comment] 2017-01-23 03:42
Yes,  the purpose of the above PR is to allow you to lint files from a multi-file package.

**Comment by osleg** [comment] 2017-01-24 10:42
Is there a particular reason why to provide a lit of files to the build command? 
`go build` invoked without any arguments will just build the entire project from the directory it currently appear. Wouldn't it be better just to run it as is from $PATH vim opened from and get all the checks?

**Comment by renstrom** [comment] 2017-01-24 10:50
@osleg I guess the issue is that it will only work for saved changes, not "on the fly". Therefore such linter only makes sense to run on-save, not cursor move (or whatever is triggering it right now).

**Comment by osleg** [comment] 2017-01-24 11:12
@renstrom well the entire "go build" checker makes sense to run on save rather on the fly imo. 
With current implementation it gives false positives on stuff like 

```main.go
package main

type A struct{}
```

```sub.go
package main

a = A{}  // <<< Error here "Undefined: A"
```

Which is annoyance and somewhy I can't find how to modify/disable it except of modifying ale itself.

**Comment by renstrom** [comment] 2017-01-24 11:18
>well the entire "go build" checker makes sense to run on save rather on the fly imo.

And I actually agree. Was mostly just stating the issue with just running `go build` from the *actual* project path. However a on-the-fly checker could be done by just copying the entire project, but depending on the size of the project it's probably not feasible.

**Comment by osleg** [comment] 2017-01-24 11:20
Any idea though on how to disable go build check? :)

**Comment by DiscoViking** [comment] 2017-01-24 12:35
@osleg @renstrom My PR related to this issue #270 fixes exactly the problems you're talking about, allowing on-the-fly linting of large packages without copying all the files.

@osleg 's example code above works fine (modulo changing the last line to `var a = A{}`,  a bug which the linter caught!)

**Comment by osleg** [comment] 2017-01-24 12:38
i meant `a := A{}` of course. 
Do you mean it works with your PR or in current master?

**Comment by DiscoViking** [comment] 2017-01-24 12:41
It works with the PR.   You are correct that it is broken on master,  which is what this issue is about. 😄

**Comment by osleg** [comment] 2017-01-24 12:42
@DiscoViking I see from the PR description that it doesn't work with .c/.h files in dir, does it mean that only .go files in dir are accepted?

**Comment by osleg** [comment] 2017-01-24 12:52
Just checked PR #270 works perfectly for me

**Comment by w0rp** [comment] 2017-02-11 22:58
I'll close this issue. The linter should kind of work now, but some improvements are currently being made.

**Closed by w0rp** 2017-02-11 22:58 UTC
Labels: bug
