### ISSUE TITLE
Add LSP textDocument/rename

### ISSUE THREAD

**Issue by Risto-Stevcev** [w0rp/ale#2419] opened 2019-04-05 15:20 UTC
Add the LSP functionality to rename. I have a WIP [here](https://github.com/Risto-Stevcev/ale/commit/a94bf9b095d8a542f17c9ceeece311d2ab283077) but it's not working

**Comment by w0rp** [comment] 2019-04-10 17:38
Duplicate of #1519.

**Closed by w0rp** 2019-04-10 17:38 UTC
