### ISSUE TITLE
lint_on_enter not being respected?

### ISSUE THREAD

**Issue by mark-westerhof** [w0rp/ale#508] opened 2017-04-26 18:14 UTC
As far as i can tell, ale_lint_on_enter is not being respected. I currently have it set to 0, but when opening/entering a JS file, jscs clearly starts running.

Debug information:
```
 Current Filetype: vim
Available Linters: ['vint']
  Enabled Linters: ['vint']
 Linter Variables:

let g:ale_vim_vint_show_style_issues = 1
 Global Variables:

let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 1000
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['jscs', 'jshint'], 'python': ['flake8']}
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '‚úó'
let g:ale_sign_offset = 1000000
let g:ale_sign_warning = '‚ö†'
let g:ale_statusline_format = ['‚úó (%d)', '‚ö† (%d)', '']
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

**Comment by adriaanzon** [comment] 2017-04-26 18:26
duplicate of https://github.com/w0rp/ale/issues/505

**Comment by w0rp** [comment] 2017-04-26 22:01
See #505

**Closed by w0rp** 2017-04-26 22:01 UTC
Labels: bug, duplicate
