### ISSUE TITLE
deoplete integration not working

### ISSUE THREAD

**Issue by sodiumjoe** [w0rp/ale#2560] opened 2019-06-05 05:45 UTC
## Information

**VIM version**

```
NVIM v0.3.4
Build type: Release
```

Operating System: 
macOS Mojave 10.14.5 (18F132)

## What went wrong

I've set up ale, and lsp error reporting works, but the deoplete completion does not.

## Reproducing the bug

I've set up ale with this minimal vimrc:
```vimscript
call plug#begin('~/.vim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'w0rp/ale'

call plug#end()

let g:ale_linters = {
      \   'javascript': ['eslint', 'flow'],
      \}

let g:deoplete#enable_at_startup = 1

call deoplete#custom#option({
      \   'min_pattern_length': 1,
      \   'auto_complete_delay': 50,
      \})
```

LSP completions from flow do not appear:
![image](https://user-images.githubusercontent.com/845857/58932667-71853c00-8719-11e9-9721-5554d216e7e2.png)

With LanguageClient-neovim, deoplete lsp completion works:
![image](https://user-images.githubusercontent.com/845857/58932798-fc663680-8719-11e9-8a68-b70f940bf521.png)

### :ALEInfo
```

 Current Filetype: javascript
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint', 'flow', 'lsp']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/16/router.jsx''']
(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/17/router.jsx''; echo']
(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/18/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/19/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[{"kind":"infer","level":"error","suppressions":[],"message":[{"context":"c","descr":"Cannot resolve name `c`.","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":7,"column":1,"offset":165},"end":{"line":7,"column":1,"offset":166}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":7,"endline":7,"start":1,"end":1}]}],"passed":false}
<<<OUTPUT ENDS>>>

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/20/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/21/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[{"kind":"infer","level":"error","suppressions":[],"message":[{"context":"crea","descr":"Cannot resolve name `crea`.","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":7,"column":1,"offset":165},"end":{"line":7,"column":4,"offset":169}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":7,"endline":7,"start":1,"end":4}]}],"passed":false}
<<<OUTPUT ENDS>>>

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/22/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/23/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/24/router.jsx''']

<<<OUTPUT STARTS>>>
/Users/<redacted>/frontend/src/redux/router.jsx:7:1: 'router' was used before it was defined. [Error/no-use-before-define]
/Users/<redacted>/frontend/src/redux/router.jsx:7:1: Expected an assignment or function call and instead saw an expression. [Error/no-unused-expressions]
/Users/<redacted>/frontend/src/redux/router.jsx:7:7: Insert `;` [Error/prettier/prettier]

3 problems
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/25/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[{"kind":"infer","level":"error","suppressions":[],"extra":[{"message":[{"context":null,"descr":"References:","type":"Blame","path":"","line":0,"endline":0,"start":1,"end":0}]},{"message":[{"context":"const router = (state: RouterShape, action: Object): RouterShape => {","descr":"[1]","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":52,"column":7,"offset":1350},"end":{"line":52,"column":12,"offset":1356}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":52,"endline":52,"start":7,"end":12}]}],"message":[{"context":"router","descr":"Cannot use variable `router` [1] because the declaration either comes later or was skipped.","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":7,"column":1,"offset":165},"end":{"line":7,"column":6,"offset":171}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":7,"endline":7,"start":1,"end":6}]}],"passed":false}
<<<OUTPUT ENDS>>>

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/26/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/27/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[{"kind":"infer","level":"error","suppressions":[],"extra":[{"message":[{"context":null,"descr":"References:","type":"Blame","path":"","line":0,"endline":0,"start":1,"end":0}]},{"message":[{"context":"const router = (state: RouterShape, action: Object): RouterShape => {","descr":"[1]","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":52,"column":7,"offset":1350},"end":{"line":52,"column":12,"offset":1356}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":52,"endline":52,"start":7,"end":12}]}],"message":[{"context":"router","descr":"Cannot use variable `router` [1] because the declaration either comes later or was skipped.","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":7,"column":1,"offset":165},"end":{"line":7,"column":6,"offset":171}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":7,"endline":7,"start":1,"end":6}]}],"passed":false}
<<<OUTPUT ENDS>>>

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/28/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/29/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/30/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/31/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[{"kind":"infer","level":"error","suppressions":[],"extra":[{"message":[{"context":null,"descr":"References:","type":"Blame","path":"","line":0,"endline":0,"start":1,"end":0}]},{"message":[{"context":"const router = (state: RouterShape, action: Object): RouterShape => {","descr":"[1]","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":52,"column":7,"offset":1350},"end":{"line":52,"column":12,"offset":1356}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":52,"endline":52,"start":7,"end":12}]}],"message":[{"context":"router","descr":"Cannot use variable `router` [1] because the declaration either comes later or was skipped.","type":"Blame","loc":{"source":"/Users/<redacted>/frontend/src/redux/router.jsx","type":"SourceFile","start":{"line":7,"column":1,"offset":165},"end":{"line":7,"column":6,"offset":171}},"path":"/Users/<redacted>/frontend/src/redux/router.jsx","line":7,"endline":7,"start":1,"end":6}]}],"passed":false}
<<<OUTPUT ENDS>>>

(started) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/32/router.jsx''']
(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/33/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[],"passed":true}
<<<OUTPUT ENDS>>>

(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/eslint/bin/eslint.js'' -f unix --stdin --stdin-filename ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/34/router.jsx''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/usr/local/bin/zsh', '-c', '''/Users/<redacted>/frontend/node_modules/.bin/flow'' check-contents --respect-pragma --json --from ale ''/Users/<redacted>/frontend/src/redux/router.jsx'' < ''/var/folders/nj/4lz3h79502z9v0w8t7_lz13r0000gn/T/nvimj7rfwM/35/router.jsx''; echo']

<<<OUTPUT STARTS>>>
{"flowVersion":"0.96.0","jsonVersion":"1","errors":[],"passed":true}
<<<OUTPUT ENDS>>>
```

**Comment by w0rp** [comment] 2019-06-08 21:40
```
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow']
```

There's your issue. You need to enable the language server instead of `flow` itself. Though bear in mind that there's an issue with the language server which makes it replace its diagnostics, which can be fixed with an undocumented option. See #2000. You might want to enable both `flow` and `flow-language-server` and use `ale_linters_ignore` to ignore the diagnostics from the flow language server until the issue is fixed for the flow language server.

**Closed by w0rp** 2019-06-08 21:40 UTC

**Comment by sodiumjoe** [comment] 2019-06-09 06:44
Interesting, thanks! I didn't think that was the problem because diagnostics were working correctly. Thanks for your great work!
