### ISSUE TITLE
Floating window in neovim

### ISSUE THREAD

**Issue by sassanh** [w0rp/ale#2424] opened 2019-04-08 14:50 UTC
Look at this for example: https://asciinema.org/a/234259
It's using neovim's new floating window to show details of each item in autocomplete menu.
Or this https://github.com/junegunn/fzf.vim/issues/664 that uses same feature to show fzf window.

It would be great if ale had an option to enable showing preview window as a floating window, currently the preview window that opens and closes when cursor moves (`g:ale_cursor_detail=1`) is a bit annoying and the echo messages with `g:ale_echo_cursor=1` are sometimes too big for the cmdline.

**Comment by w0rp** [comment] 2019-04-10 17:38
Duplicate of #2418.

**Closed by w0rp** 2019-04-10 17:38 UTC
