### ISSUE TITLE
No way to change pylint message format

### ISSUE THREAD

**Issue by sblask** [w0rp/ale#1056] opened 2017-10-27 08:15 UTC
I don't like seeing the error code and would like to change the message format using b:ale_python_pylint_options, but it doesn't work. If I understand correctly what's going on, swapping line 18/19 in https://github.com/w0rp/ale/blob/master/ale_linters/python/pylint.vim should do the trick.

**Comment by w0rp** [comment] 2017-10-27 08:37
This is a duplicate of #852. See that issue.

**Closed by w0rp** 2017-10-27 08:37 UTC
