### ISSUE TITLE
Error with autocompletion in Rust -- E731: using Dictionary as String

### ISSUE THREAD

**Issue by danielwelch** [w0rp/ale#1794] opened 2018-08-06 20:30 UTC
## Information

**VIM version**

NVIM v0.3.1
Build type: Release

Operating System: macOS High Sierra 10.13.4 (17E202)
### :ALEInfo

 Current Filetype: rust
Available Linters: ['cargo', 'rls', 'rustc']
  Enabled Linters: ['rls']
 Suggested Fixers: 
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'rustfmt' - Fix Rust files with Rustfmt.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_rust_rls_executable = 'rls'
let g:ale_rust_rls_toolchain = 'nightly'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {}
let b:ale_fixers = ['rustfmt']
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 2000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = ['rls']
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 0
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) ['/bin/bash', '-c', '''rls'' +''nightly''']
## What went wrong

When inserting text in insert mode, I get the following error when working on Rust files and using ALE autocompletion:
`E731: using Dictionary as String` 

## Reproducing the bug

1. Open a rust file with `let g:ale_completion_enabled = 1`
2. Start typing something that would trigger autocompletion.

I do not have this problem when working on other filetypes (tested with python). I'm using RLS on `rustc 1.30.0-nightly (73c78734b 2018-08-05)`

After dismissing the errors, the autocompletion pop-up is filled with appropriate completion options, as expected. Just the error that pops up and disrupts things.

**Comment by danielwelch** [comment] 2018-08-06 22:51
This seems to have resolved after updating RLS, maybe it was due to a problem with today's nightly Rust and RLS

**Comment by danielwelch** [comment] 2018-08-09 17:37
Never mind, has not resolved with latest Rust and RLS.

**Comment by w0rp** [comment] 2018-08-10 17:17
Are there any more lines in the error message? It would be good to know which function that error is for.

**Comment by Luxed** [comment] 2018-08-15 17:09
@danielwelch This doesn't happen on the `stable` rust toolchain, but it happens on the `beta` and `nightly` toolchains.
@w0rp Unfortunately, there is no more information in the error message.

**Comment by danielwelch** [comment] 2018-08-15 17:29
@luxed Pardon my ignorance, but can’t RLS only be run on the nightly toolchain?

I only work with stable rust for the most part, so if there was a way to just avoid the nightly toolchain and still use rls for diagnostics/linting then I would.

**Comment by Luxed** [comment] 2018-08-15 17:53
Well, it could only be on the nightly when Rust stable was  < 1.27 (or 1.26, I don't remember). Anyway, the fact is that, with Rust stable 1.28, an older version of the RLS is still present.

Simply run this: `rustup component add rls-preview rust-analysis rust-src --toolchain stable`
and then add this line to your init.vim: `let g:ale_rust_rls_toolchain = 'stable'`

And everything should work as intended ! (hopefully)

**Comment by Deedasmi** [comment] 2018-08-19 19:59
I used to get this error, but now I'm getting `E715: Dictionary Required`. How would I go about getting better error messages?

**Comment by danielwelch** [comment] 2018-08-19 20:11
For what it’s worth, since moving to the stable toolchain for RLS, this error has disappeared. I’m wondering if the problem is caused by certain nightly version of Rust nightly that break RLS

**Comment by w0rp** [comment] 2018-08-20 08:39
@Deedasmi If you look at `:mess`, you can often see the previous error messages with the line numbers in the functions they happened it.

**Comment by Deedasmi** [comment] 2018-08-24 23:04
Sorry for the delay!

```
Error detected while processing function <SNR>90_VimOutputCallback[6]..<SNR>91_HandleCommandMessage[3]..ale#lsp#HandleMessage[16]..ale#lsp#HandleOtherInitializeResponses:
line   14:
E715: Dictionary required
E715: Dictionary required
```

**Comment by w0rp** [comment] 2018-08-28 09:40
That other error message is another one, and that has been fixed now. I would like to know what line the E731 error can happen on.

**Comment by micouy** [comment] 2018-08-28 09:44
I don't know if it helps but the comment at line 4 in [completion.vim](https://github.com/w0rp/ale/blob/master/autoload/ale/completion.vim) says `The omnicompletion menu is shown through a special Plug mapping which is only valid in Insert mode. This way, feedkeys() won't send these keys if you quit Insert mode quickly enough.`.

**Comment by w0rp** [comment] 2018-08-28 09:51
Yes. You'll be seeing the text there because an error was thrown somewhere else.

**Comment by davidtwco** [comment] 2018-09-17 09:57
@w0rp I've been having this error a lot with the most recent stable RLS, in `:mess` there's no line numbers, but using `-V20` I've managed to get the following:

```
continuing in function ale#completion#OmniFunc

line 23:
line 24:         return get(b:, 'ale_completion_result', [])
function ale#completion#OmniFunc returning [{'word': 'UserData', 'menu': 'pub tra...rData.html'}, 'kind': 'f', 'icase': 1}]

E731: using Dictionary as a String
E731: using Dictionary as a String
```

I've [created a gist](https://gist.github.com/davidtwco/b71fa05a9baa20e236cea6e3fccaa709) with all of my versions and `ALEInfo` output. RLS is the version currently distributed against stable with the `rls-preview` component in rustup.

**Comment by w0rp** [comment] 2018-09-17 10:18
@davidtwco Thank you, that was what I needed to know. I pushed a commit now which should handle documentation for completion items which are sent as Dictionary values. It looks like that was the problem. We have the option of processing Markdown content in future. For now, the raw Markdown text may be displayed for messages from `rls`.

**Comment by davidtwco** [comment] 2018-09-17 10:32
@w0rp Excellent! I can confirm that this has fixed the issue.

**Comment by w0rp** [comment] 2018-09-17 13:17
Nice. :+1: Thank you for letting me know where the error is.

**Closed by w0rp** 2018-09-17 13:17 UTC
Labels: bug
