### ISSUE TITLE
Does there any command for On/Off/Toggle ALE?

### ISSUE THREAD

**Issue by markwu** [w0rp/ale#161] opened 2016-11-02 02:59 UTC
Hi,

I just check the document, it seems ALE has no commands for On/Off/Toggle. Does there way to achieve this?

**Comment by w0rp** [comment] 2016-11-02 09:07
There aren't any options at the moment for turning linting on or off while Vim is still open. This has been asked for before, so maybe I should add a function for it.

**Comment by w0rp** [comment] 2016-12-01 09:41
I'll close this as, this is a duplicate of #122.

**Closed** 2016-12-01 09:41 UTC
Labels: duplicate, enhancement
