### ISSUE TITLE
Out of range highlights trigger errors in NeoVim

### ISSUE THREAD

**Issue by chenjie199234** [w0rp/ale#2505] opened 2019-05-15 05:46 UTC
this will only happened on LSP
file type:go
linter:gopls
nvim:0.3.5
when a go file has a error.
when open it and change buffer to it,this will happen
![2019-05-15-13:30:17](https://user-images.githubusercontent.com/29348971/57751279-bf5ce480-7717-11e9-999d-b1b7ba9cdcc5.png)

**Comment by w0rp** [comment] 2019-05-15 10:40
I can't read Chinese in screenshot, so I can't help much there. Have you tried using `git pull` to get the latest version and trying it again? It might be related to #2475, which was already merged.

**Comment by w0rp** [comment] 2019-05-15 14:10
Can you translate the error message from Chinese to English, for the benefit of others, or reproduce it with the locale settings set to English?

**Comment by chenjie199234** [comment] 2019-05-15 14:12
@w0rp 
![2019-05-15-22:13:12](https://user-images.githubusercontent.com/29348971/57782231-65cbd880-775e-11e9-9bf9-dfbe9e100586.png)

**Comment by chenjie199234** [comment] 2019-05-15 14:23
@w0rp 
this can be repeated very easily
use golang's lsp linter ```gopls``` and config it right
create two ```.go``` files in a dir under ```gopath```
write some code in the two ```.go``` files
open both two files,and write some wrong code in one file.
now use ```:bnext``` or ```:bprev``` to change buffer.
this problem will happen
![2019-05-15-22:20:56](https://user-images.githubusercontent.com/29348971/57782969-db847400-775f-11e9-8088-29aafa7c7014.png)
![2019-05-15-22:21:43](https://user-images.githubusercontent.com/29348971/57782992-e4754580-775f-11e9-85df-2517d373e051.png)

**Comment by w0rp** [comment] 2019-05-15 15:03
That looks like the problem that was already fixed in #2475. Maybe @andreypopp can have a look.

**Comment by chenjie199234** [comment] 2019-05-16 06:06
@w0rp 
the using linters `gopls` `gofmt` `golint` `govet`
### situation 1 use linter `gopls`
there is a 100% to triger this problem when switch buffer between file with errors and file has no error
### situation 2 delete linter `gopls`
there is still a low chance about 10% to triger this problem when switch fastly between file with errors and file has no error

**Comment by w0rp** [comment] 2019-05-16 12:45
Okay, `git pull` and try it again. I made it grab the lines from the buffer to get the number of lines, and constrain the highlight ranges by the number of lines. I would update the tests, but none of the tests that were written are run by Travis CI anyway, because the Docker image hasn't been updated to also test with a version of NeoVim that's new enough.

**Comment by chenjie199234** [comment] 2019-05-16 15:33
@w0rp nothing changed
did i config the ale right?
here is the images.
![2019-05-16-23:31:45](https://user-images.githubusercontent.com/29348971/57866996-ea882680-7832-11e9-97f8-4bf8bed84bad.png)
![2019-05-16-23:32:24](https://user-images.githubusercontent.com/29348971/57867012-f2e06180-7832-11e9-97d8-829fdd088ebf.png)

**Comment by andreypopp** [comment] 2019-05-16 18:56
@chenjie199234 wasn't able to repro with this exact version of neovim and set of linters. Any chance you can have a docker container with repro?

**Comment by w0rp** [comment] 2019-05-16 18:58
Right, I'm git reverting it until it works in that case.

**Comment by w0rp** [comment] 2019-05-16 19:04
Now I've removed support for it. I'll reopen the issue for adding support for it until it works again.

**Closed** 2019-05-16 19:04 UTC
Labels: triage
