### ISSUE TITLE
tslint command broken for tslint > 5.10

### ISSUE THREAD

**Issue by chemzqm** [w0rp/ale#1579] opened 2018-05-14 15:12 UTC
It's not ALE issue, it's `ale_linters/typescript/tslint.vim` could not get working command.
Check out https://stackoverflow.com/questions/46715843/what-is-the-meaning-of-tslint-warning-the-no-use-before-declare-rule-requir

There is a `--project` option required for some tslint rules to work, but the linter not using that at all.
I find that the `--project` doesn't allows full path.  Here is my dirty fix:
``` vim
diff --git a/ale_linters/typescript/tslint.vim b/ale_linters/typescript/tslint.vim
index b28f7cee..d5223e2a 100644
--- a/ale_linters/typescript/tslint.vim
+++ b/ale_linters/typescript/tslint.vim
@@ -3,6 +3,7 @@

 call ale#Set('typescript_tslint_executable', 'tslint')
 call ale#Set('typescript_tslint_config_path', '')
+call ale#Set('typescript_tslint_project_path', '')
 call ale#Set('typescript_tslint_rules_dir', '')
 call ale#Set('typescript_tslint_use_global', get(g:, 'ale_use_global_executables', 0))
 call ale#Set('typescript_tslint_ignore_empty_files', 0)
@@ -60,6 +61,19 @@ function! ale_linters#typescript#tslint#GetCommand(buffer) abort
     \   'tslint.json',
     \   ale#Var(a:buffer, 'typescript_tslint_config_path')
     \)
+
+    let l:tslint_project_path = ale#path#ResolveLocalPath(
+    \   a:buffer,
+    \   'tsconfig.json',
+    \   ale#Var(a:buffer, 'typescript_tslint_project_path')
+    \)
+
+    let root = fnamemodify(l:tslint_project_path, ':h')
+    let fullpath = fnamemodify(bufname(a:buffer), ':p')
+    let l:file = fullpath[len(root) + 1 : ]
+    let l:tslint_config_path = l:tslint_config_path[len(root) + 1 : ]
+
+
     let l:tslint_config_option = !empty(l:tslint_config_path)
     \   ? ' -c ' . ale#Escape(l:tslint_config_path)
     \   : ''
@@ -69,12 +83,14 @@ function! ale_linters#typescript#tslint#GetCommand(buffer) abort
     \  ? ' -r ' . ale#Escape(l:tslint_rules_dir)
     \  : ''

-    return ale#path#BufferCdString(a:buffer)
+    let g:a = ale#path#CdString(root)
     \   . ale#Escape(ale_linters#typescript#tslint#GetExecutable(a:buffer))
     \   . ' --format json'
+    \   . ' -p .'
     \   . l:tslint_config_option
     \   . l:tslint_rules_option
-    \   . ' %t'
+    \   . ' '.l:file
+    return g:a
 endfunction
```

**Comment by w0rp** [comment] 2018-05-15 11:56
I'll mark this as a duplicate of this here: #925 

TSLint just is not good at doing on the fly checking at the moment. I created a pull request in TSLint itself to address this: https://github.com/palantir/tslint/pull/3816 It hasn't been looked at seriously yet, but I've been told they will look at it when they have the time. I understand.

**Closed by w0rp** 2018-05-15 11:56 UTC

**Comment by w0rp** [comment] 2018-05-15 11:58
What I recommend instead for now is this: https://github.com/angelozerr/tslint-language-service

You can run TSLint via `tsserver`, as a plugin. I haven't tried it myself, but I hear good things.
