### ISSUE TITLE
A tsserver bug was able to lock up Vim completely

### ISSUE THREAD

**Issue by chris-morgan** [w0rp/ale#2185] opened 2019-01-07 09:40 UTC
## Information

**VIM version**

VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support

**Operating System:** Windows 10 Pro 64-bit, version 1803 (build 17134.472)

## What went wrong

At some point when I was typing in some JavaScript in insert mode, Vim locked up. Examination of the process tree suggested that tsserver was probably the culprit, and https://github.com/Microsoft/TypeScript/issues/18255 matches the observed symptoms, and so I’m about to update my TypeScript installation from 2.5.2 to 3.2, which should fix the symptoms.

But tsserver shouldn’t have been able to cause Vim to hang, right? ALE is all about asynchrony, isn’t it, which should make that never happen? It seems clear to me that although tsserver *triggered* the symptoms, the actual bug that I observed of Vim locking up is going to be either ALE’s or Vim’s fault, so here’s this issue.

## Reproducing the bug

1. Opened a new buffer
2. Set its filetype to javascript
3. Pasted in a moderately substantial quantity of code
4. Went through it making various style modifications, replacing `x: function(){}.foo()` with `@foo x(){}`, *&c.*
5. Somewhere along the way, it froze.

### :ALEInfo

<details>
<summary><em>Straightforward: filetype javascript, tscs linter is enabled, and <code>(started) 'cmd /s/c "tsserver"'</code> happened</em></summary>

```
Current Filetype: javascript
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_flow_executable = 'flow'
let g:ale_javascript_flow_ls_executable = 'flow'
let g:ale_javascript_flow_ls_use_global = 0
let g:ale_javascript_flow_use_global = 0
let g:ale_javascript_flow_use_home_config = 0
let g:ale_javascript_flow_use_respect_pragma = 1
let g:ale_javascript_jscs_executable = 'jscs'
let g:ale_javascript_jscs_use_global = 0
let g:ale_javascript_jshint_executable = 'jshint'
let g:ale_javascript_jshint_use_global = 0
let g:ale_javascript_standard_executable = 'standard'
let g:ale_javascript_standard_options = ''
let g:ale_javascript_standard_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
let g:ale_javascript_xo_executable = 'xo'
let g:ale_javascript_xo_options = ''
let g:ale_javascript_xo_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 'on_save'
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) eslint
(executable check - failure) jscs
(executable check - failure) jshint
(executable check - failure) standard
(started) 'cmd /s/c "tsserver"'
(executable check - failure) xo
```

</details>

**Comment by w0rp** [comment] 2019-01-07 17:53
I use tsserver every day at work, and it doesn't free for me. We'll need to make this bug more reproducible other than "install tsserver and modify a few things." If you can get Vim to freeze and then resume running again, profile the Vim script code as described here: https://stackoverflow.com/a/12216578/1836507

It might be possible to fix this issue with the `noblock` option for channels only available in Vim 8.1 patch 350 and up, or maybe there's another bug in Vim we'll have to get them to fix.

**Comment by w0rp** [comment] 2019-01-11 13:11
Sure, let me know what you find. The issue will be generally around channels, how many can be open, how much data is being sent, how it's being set, etc. It's partly a Vim issue, and partly how ALE uses Vim.

One part of your issue might be that because you're seeing hundreds of errors, the editor just can't cope with that much data. You might have more luck running `tsc` to find all of the errors, fixing most of them first, and then using `tsserver`. There has to be an upper limit somewhere around how much data the editor can handle. I'd put that limit somewhere in the hundreds of errors.

**Comment by w0rp** [comment] 2019-01-11 13:12
Or in others words, run `tsc` to find the lion's share of issues, and disable `tsserver` support (`b:ale_linters`) or ALE (`:ALEDisable`). Fix those issues, and run `tsc` until most of them are resolved. Then turn on `tsserver` support again.

**Comment by w0rp** [comment] 2019-05-17 18:40
Nothing came of this, so I'll close it.

**Closed by w0rp** 2019-05-17 18:40 UTC
Labels: bug, cant repeat
